### PR TITLE
Feature/release preparation

### PR DESCRIPTION
**Pull request by HazAT**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Is there a swift linter we can use for codestyle?

**Comment by HazAT** [comment]
Yeah its already in place but not enforced, https://github.com/realm/SwiftLint

**Comment by mitsuhiko** [comment]
Ah neat. Yeah, maybe we can enforce it with some hand tuning.

**Comment by HazAT** [comment]
Ok ... so its a buildstep already, outputs a warning if not installed.
@mitsuhiko So you think I should error the build if swiftlint is not installed?

**Comment by mitsuhiko** [comment]
@HazAT in the other repos we do two things. We have one dedicated test run with linters and we also set up local git hooks to lint before commit.

https://github.com/getsentry/sentry/blob/87aad4bf3fbf846931f9f4212078c5eb6403b2aa/Makefile#L37-L41

**Comment by HazAT** [comment]
Will test develop branch after merge to prepare 1.0.0 release

**Pull request merged**
