### PR TITLE
Update to Xcode 8GM and Swift 3

### PR DESCRIPTION
**Pull request by MihaelIsaev**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-swift/58)

### CODE REVIEW

**Comment by hannseman** [comment]
`.travis.yml` should be updated to use `osx_image: xcode8`

**Comment by joshdholtz** [comment]
@MihaelIsaev Thanks for the contribution! I have a branch that I'm finishing up that works with Swift 2.3 and Swift 3. Do your changes here also work with Swift 2.3?

**Comment by MihaelIsaev** [comment]
@joshdholtz It's great to hear! I think my branch only works with Swift 3, but I'm not tested it with Swift 2.3. Anyway if your branch tested with both Swift 2.3 and Swift 3 and works great, then it's better than mine. But for now I use my branch in big Swift 3 project and I have to say that it works perfect.

**Comment by joshdholtz** [comment]
@MihaelIsaev My branch is up in #59 if you want to give it a try sometime 😊 I have tests running on it right now and will need to do some actual testing on apps with crashes yet but should be merged into master soon once good 👌

**Comment by joshdholtz** [comment]
@MihaelIsaev Going to close this in favor of #59 but thanks so much for the contribution!

**Comment by joshdholtz** [comment]
UPDATE: A release has been made for Swift 2.3 and Swift 3.0 support under `0.4.0` for Carthage and CocoaPods

**Pull request closed without merging**
