### PR TITLE
[WIP] KSCrash 1.13 / Objc Namespace

### PR DESCRIPTION
**Pull request by HazAT**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Does this mean users now have to adjust their code?

**Comment by HazAT** [comment]
Yes .. but just their objc code, we needed it because of this:
https://github.com/getsentry/sentry-swift/issues/31#issuecomment-268983277

**Comment by mitsuhiko** [comment]
In that case we should make sure to bump the API and mention it in the docs

**Comment by HazAT** [comment]
Do you mean even go for `2.x` or is `1.4.x` engough?
Because its a "soft" break, Xcode even suggest to rename `User` to `SentryUser` when compiling?

**Comment by mitsuhiko** [comment]
1.4 might be enough. Just need to make sure we mention the change somewhere in a changelog in the docs.

**Pull request merged**
