### PR TITLE
Improve User Feeback

### LINKED ISSUE #84: User Feedback Improvements
* [x] fonts are too bright
* [x] submit button does not seem to do anything?
* [x] smaller/lighter sentry logo

### PR DESCRIPTION
**Pull request by HazAT**
Fix #84

### CODE REVIEW

**Comment by HazAT** [comment]
Before:
simulator screen shot 1 dec 2016 12 28 56

After:
simulator screen shot 1 dec 2016 13 06 19


Keep in mind that the way @ckj designed to the modal presentation style (like mail app) ... this isn't available as an apple API thats a custom transition.
And for all the colors I used the Apple default colors and took the darker one now

**Comment by mitsuhiko** [comment]
I think we should nake email optional if text or name is provided. Eg. We just require either name or mail if someone left text and make text optional if the user left name and email.

**Comment by HazAT** [comment]
I am pretty sure that all fields are mandatory by server validation.

**Comment by mitsuhiko** [comment]
Kk. then let's leave it for now. We should probably relax that later then.

**Comment by HazAT** [comment]
Can we merge this?

**Pull request merged**
