### PR TITLE
Changes extracting the project ID from DSN URL

### PR DESCRIPTION
**Pull request by milancermak**
NSURL already has a way how to get the ID you need from it.

### CODE REVIEW

**Comment by joshdholtz** [comment]
@milancermak Thanks for PR! I think I originally had it the way you suggested but I wanted to make sure the ID was still pulled out properly if (for some reason) there was more than two items in that paths array. The way of dropping the first and then getting the first guarantees that second element is selected. Using `lastComponent` will most likely always pull the second element but _may_ pull out a third or forth if the URL is constructed wrong.

Let me know if that makes sense or not 😇

**Comment by milancermak** [comment]
Got it. You know better about the URL than I do.

However I'm wondering, if it wouldn't be better then to check if the URL is constructed correctly? Or fail in the initializer?

**Comment by ahti** [comment]
The Sentry client API docs state regarding incomplete DSN strings:

> If any of configuration values are not present, the client should notify the user immediately that they’ve misconfigured the client.

While this does not mention DSN strings with too many path components, I think notifying the user by causing an assertion failure would be appropriate.

**Comment by joshdholtz** [comment]
@ahti I like the idea of an assertion. I would _like_ to throw a nice Swift error if possible (have to look into have that can work with Objective-C so we can maintain compatibility) but if not then we can definitely throw some assertions in there 👌

**Comment by joshdholtz** [comment]
Closing this in favor of #23

**Pull request closed without merging**
